<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RequestsTableSeeder extends Seeder
{
    public function run(): void
    {
        $requests = [
            [
                'title' => 'Math Tutor Needed for High School Student',
                'description' => 'Looking for an experienced math tutor to help with calculus, algebra, and SAT preparation. Student is in 11th grade and needs help with advanced mathematics concepts. Sessions can be online or in-person.',
                'category' => 'Education & Tutoring',
                'city' => 'Algiers',
                'contactEmail' => 'ahmed.benali@student.com',
                'contactPhone' => '0550123456',
                'pay' => '1500 DA/hour',
                'availability' => 'Weekdays after 4PM, weekends flexible',
                'student_id' => 1,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Web Development Tutor for Beginners',
                'description' => 'Computer science student available to teach HTML, CSS, JavaScript, and basic web development concepts. Perfect for beginners wanting to learn web development from scratch.',
                'category' => 'Education & Tutoring',
                'city' => 'Algiers',
                'contactEmail' => 'mohamed.cherif@student.com',
                'contactPhone' => '0550345678',
                'pay' => '1200 DA/hour',
                'availability' => 'Evenings and weekends',
                'student_id' => 3,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'English Conversation Practice Partner',
                'description' => 'Native English speaker needed for conversation practice with language learners. Must be patient and have teaching experience. Flexible scheduling available.',
                'category' => 'Education & Tutoring',
                'city' => 'Oran',
                'contactEmail' => 'sara.hamani@student.com',
                'contactPhone' => '0410123456',
                'pay' => '1000 DA/hour',
                'availability' => 'Flexible hours',
                'student_id' => 4,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Physics and Chemistry Tutor',
                'description' => 'Experienced tutor needed for high school physics and chemistry. Must have strong knowledge of scientific concepts and exam preparation techniques.',
                'category' => 'Education & Tutoring',
                'city' => 'Constantine',
                'contactEmail' => 'rachid.messaoudi@student.com',
                'contactPhone' => '0330123456',
                'pay' => '1800 DA/hour',
                'availability' => 'Weekends preferred',
                'student_id' => 9,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Programming Languages Tutor',
                'description' => 'Computer science student offering tutoring in Python, Java, C++, JavaScript, and other programming languages. Both beginner and advanced levels welcome.',
                'category' => 'Education & Tutoring',
                'city' => 'Annaba',
                'contactEmail' => 'lila.merabet@student.com',
                'contactPhone' => '0380123456',
                'pay' => '1300 DA/hour',
                'availability' => 'Evenings and weekends',
                'student_id' => 6,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Academic Writing Assistant',
                'description' => 'Skilled writer needed to help with essays, research papers, and academic writing assignments. Experience with various citation styles and academic formatting.',
                'category' => 'Education & Tutoring',
                'city' => 'Tlemcen',
                'contactEmail' => 'karim.bensalem@student.com',
                'contactPhone' => '0431234567',
                'pay' => '1000 DA/hour',
                'availability' => 'Flexible',
                'student_id' => 5,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Music Teacher - Piano',
                'description' => 'Piano teacher offering lessons for beginners and intermediate students. Both classical and modern styles taught. Must have performance experience.',
                'category' => 'Education & Tutoring',
                'city' => 'Béjaïa',
                'contactEmail' => 'omar.kaci@student.com',
                'contactPhone' => '0251234567',
                'pay' => '2000 DA/hour',
                'availability' => 'Weekday evenings, weekends all day',
                'student_id' => 7,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Art Teacher - Drawing & Painting',
                'description' => 'Art teacher offering lessons in drawing, painting, and digital art. All skill levels welcome from beginner to advanced.',
                'category' => 'Education & Tutoring',
                'city' => 'Blida',
                'contactEmail' => 'nadia.belkacem@student.com',
                'contactPhone' => '0431234567',
                'pay' => '1500 DA/hour',
                'availability' => 'Flexible hours',
                'student_id' => 8,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sports Coach - Basketball',
                'description' => 'Experienced basketball coach for individual and team training. Focus on skill development and game strategy. All age groups.',
                'category' => 'Events & Temporary Work',
                'city' => 'Algiers',
                'contactEmail' => 'amina.djelloul@student.com',
                'contactPhone' => '0341234567',
                'pay' => '1500 DA/hour',
                'availability' => 'Evenings and weekends',
                'student_id' => 10,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Photography Assistant',
                'description' => 'Photography student looking for assistant roles for events and photoshoots. Must have basic equipment and editing skills.',
                'category' => 'Events & Temporary Work',
                'city' => 'Oran',
                'contactEmail' => 'omar.kaci@student.com',
                'contactPhone' => '0251234567',
                'pay' => '800 DA/day',
                'availability' => 'Weekends',
                'student_id' => 7,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Event Staff - Weekend Events',
                'description' => 'Looking for event staff for various weekend events including conferences, parties, and corporate events. Must be reliable and punctual.',
                'category' => 'Events & Temporary Work',
                'city' => 'Constantine',
                'contactEmail' => 'karim.bensalem@student.com',
                'contactPhone' => '0381234567',
                'pay' => '1000 DA/day',
                'availability' => 'Saturdays and Sundays',
                'student_id' => 5,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Delivery Driver',
                'description' => 'Part-time delivery driver needed for local deliveries in Annaba area. Must have valid driver\'s license and reliable transportation.',
                'category' => 'Service & Delivery',
                'city' => 'Annaba',
                'contactEmail' => 'lila.merabet@student.com',
                'contactPhone' => '0380123456',
                'pay' => '500 DA/day',
                'availability' => 'Flexible hours',
                'student_id' => 6,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Personal Shopper',
                'description' => 'Looking for personal shopper for grocery shopping in Blida area. Must be reliable and have good knowledge of local stores.',
                'category' => 'Service & Delivery',
                'city' => 'Blida',
                'contactEmail' => 'nadia.belkacem@student.com',
                'contactPhone' => '0431234567',
                'pay' => '300 DA/hour',
                'availability' => 'Flexible',
                'student_id' => 8,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Virtual Assistant',
                'description' => 'Virtual assistant needed for administrative tasks, email management, and scheduling. Must have excellent communication skills.',
                'category' => 'Service & Delivery',
                'city' => 'Algiers',
                'contactEmail' => 'rachid.messaoudi@student.com',
                'contactPhone' => '0330123456',
                'pay' => '400 DA/hour',
                'availability' => 'Flexible remote work',
                'student_id' => 9,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Content Writer for Blog',
                'description' => 'Student writer needed for blog content creation in various niches including tech, education, and lifestyle topics.',
                'category' => 'Service & Delivery',
                'city' => 'Oran',
                'contactEmail' => 'sara.hamani@student.com',
                'contactPhone' => '0410123456',
                'pay' => '50 DA/article',
                'availability' => 'Flexible',
                'student_id' => 4,
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('requests')->insert($requests);
    }
}
